apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-thrift-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vamsikrishna6572/kube-thrift-demo-infra.git
    targetRevision: main
    path: envs/dev/php-apache

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

